version: "3.4"

services:
  prometheus:
    image: quay.io/prometheus/prometheus:v2.0.0
    ports:
      - "9090:9090"
    command: "--config.file=/etc/prometheus/prometheus.yml"
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - source: alertrules.yml
        target: /etc/prometheus/alertrules.yml
    networks:
      - default
      - jukebox_default

  cadvisor:
    image: google/cadvisor:v0.25.0
    ports:
        - "8080:8080"
    volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
    deploy:
        mode: global

configs:
  prometheus.yml:
    file: ./prometheus.yml
  alertrules.yml:
    file: ./alertrules.yml

networks:
  jukebox_default:
    external: true
